steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '.', '-t', 'genegraph-gene-validity:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'genegraph-gene-validity:$COMMIT_SHA', 'us-east1-docker.pkg.dev/clingen-dx/genegraph-prod/genegraph-gene-validity:$COMMIT_SHA']

images:
- 'us-east1-docker.pkg.dev/clingen-dx/genegraph-prod/genegraph-gene-validity:$COMMIT_SHA'
